var c=document.getElementById("Canvas"),d=c.getContext("2d"),f=c.width=window.innerWidth,k=c.height=window.innerHeight,l=!1,m=!1,n=!1,p=!1,q=!1,r=!1,t=0,u=0,v=0,w=0,x=[],y=[],z=[],A=[[0]],B,C,D={index:0,text:"New Mind",G:"white",color:"#FFA500",shadowColor:"#191919",shadowBlur:18,b:f/2,a:k/2,x:0,y:0,width:105,height:30,c:15,m:0,o:0,s:0,u:0,B:0,C:0,A:0,D:0,F:0,v:0},aa={color:"aqua",shadowBlur:18,x:0,y:0,b:0,a:0,c:10},ba={f:0,i:0,color:"#FFA500",shadowColor:"black",shadowBlur:18,width:2,g:0,h:0,j:0,
l:0,m:0,o:0,s:0,u:0},E="#7FFF00 #00FFFF #FF00FF #FF4500 #4682B4 #4B0082 #FF0000 #e096e9 #e68782 #efa670 #9ed56b #67d7c4 #b4b4b4 #0da7d3 #3e8975 #69b500 #e8e525 #ffaa38 #a65427".split(" "),F,G,H,ca,da,I=!1,J=!1,K=0,L=[],M=[],N=[],O,P;function Q(){P=!1;for(var a=0;a<x.length;a++)if(t>x[a].x&t<x[a].x+x[a].width&u>x[a].y-30&u<x[a].y+x[a].height+15){P=a;break}return P}
function ea(){if(!1===m)r=Q(),m=!1!==r;else{var a=y[r];P=!1;t>a.x&t<a.b+a.c&u>a.a-a.c&u<a.a+a.c&&(P=r);r=P;!1!==r?n=!0:(n=!1,r=Q(),m=!1!==r)}}c.addEventListener("mousedown",function(a){fa(a.offsetX,a.offsetY)});c.addEventListener("mousemove",function(a){!1===J&&ha(a.offsetX,a.offsetY)});c.addEventListener("mouseup",function(a){ia(a.offsetX,a.offsetY)});document.addEventListener("keyup",function(a){a=a.key;"Delete"==a&!0===m&&ja();"Enter"==a&&deleteInput();!0===p&&R()});
window.addEventListener("resize",function(){f=c.width=window.innerWidth;k=c.height=window.innerHeight;S()});c.addEventListener("touchstart",function(a){fa(Math.round(a.touches[0].clientX),Math.round(a.touches[0].clientY));c.addEventListener("touchmove",function(b){!1===J&&ha(Math.round(b.touches[0].clientX),Math.round(b.touches[0].clientY))},!1);c.addEventListener("touchend",function(b){ia(Math.round(b.touches[0].clientX),Math.round(b.touches[0].clientY))},!1)},!1);
function fa(a,b){v=a;w=b;t=a;u=b;ea();!1!==r&&(K=r);!0===m&!1===n&&(M=ka(),N=la(),!0===I&&T());l=!0}function ha(a,b){if(!0===l){!0===m&!1===n&&(T(),ma(a,b),U(r),V(N),S());if(!0===n){T();var e=y[r];e.b=a;e.a=b;e.x=e.b-e.c;e.y=e.a-e.c;W();X();d.beginPath();d.shadowOffsetX=0;d.shadowOffsetY=0;d.shadowColor="aqua";d.shadowBlur=18;d.strokeStyle="#3c2c3e";d.lineWidth=2;d.moveTo(x[r].b,x[r].a);d.lineTo(a,b);d.stroke();Y();na(r)}!1===m&!1===n&&(T(),oa(a,b),pa(),V(),S(r))}t=a;u=b}
function ia(a,b){l=!1;v==a&w==b&&(!0===m?(T(),qa()):T());if(!0===m&!0===n){U(r);var e=Q();if(!1===e){e=Object.assign({},D);e.text="branch "+String(x.length);e.width=Math.round(d.measureText(e.text).width+25);e.b=a;e.a=b;for(var g=E[Math.floor(Math.random()*(E.length-0))+0];g==H;)g=E[Math.floor(Math.random()*(E.length-0))+0],console.log("\u0421\u043e\u0432\u043f\u0430\u0434\u0435\u043d\u0438\u0435 \u0446\u0432\u0435\u0442\u0430 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e");e.color=
g;e.index=x.length;x.push(e);Z(x.length-1);ra();e=Object.assign({},aa);y.push(e);sa()}else ra(e);S();ea()}v==a&w==b&&!0===m&!1===p&!1===n&&!1===p&&(p=!0,document.body.insertAdjacentHTML("afterend",'<input id="input-text">'),C=document.getElementById("input-text"),"branch"==x[r].text.split(" ")[0]||"New Mind"==x[r].text?(da=x[r].text,C.value=""):C.value=x[r].text,B=Math.round(d.measureText(x[r].text).width),x[r].width=B+35,F=B+25,C.style.width=B+10+"px",C.style.left=x[r].b-B/2-5+"px",C.style.top=x[r].a-
10+"px",C.focus(),R())}function pa(){x.forEach(function(a,b){Z(b)})}function Z(a){a=x[a];a.x=a.b-a.width/2;a.y=a.a-a.height/2;var b=a.c/3;a.m=a.y+a.c;a.o=a.y+b;a.s=a.x+b;a.u=a.x+a.c;a.B=a.x+a.width-a.c;a.C=a.x+a.width-b;a.A=a.x+a.width;a.D=a.y+a.height-a.c;a.F=a.y+a.height-b;a.v=a.y+a.height}function U(a){var b=y[a];a=x[a];b.b=a.b;b.a=a.a-a.height/2-20;b.x=b.b-b.c;b.y=b.a-b.c}
function V(a){a=void 0===a?z:a;a.forEach(function(b){b.g=x[b.f].b;b.h=x[b.f].a;b.j=x[b.i].b;b.l=x[b.i].a;Math.abs(b.g-b.j)>Math.abs(b.h-b.l)?(b.m=b.g,b.o=b.l,b.s=b.j,b.u=b.h,b.b=b.g+(b.j-b.g)/2,b.a=b.h+(b.l-b.h)/2):(b.m=b.j,b.o=b.h,b.s=b.g,b.u=b.l,b.b=b.g-(b.g-b.j)/2,b.a=b.h-(b.h-b.l)/2)})}function W(){d.clearRect(0,0,f,k)}
function Y(){x.forEach(function(a){d.beginPath();d.shadowColor=a.shadowColor;d.shadowBlur=a.shadowBlur;d.fillStyle=a.color;d.moveTo(a.x,a.m);d.bezierCurveTo(a.x,a.o,a.s,a.y,a.u,a.y);d.lineTo(a.B,a.y);d.bezierCurveTo(a.C,a.y,a.A,a.o,a.A,a.m);d.lineTo(a.A,a.D);d.bezierCurveTo(a.A,a.F,a.C,a.v,a.B,a.v);d.lineTo(a.u,a.v);d.bezierCurveTo(a.s,a.v,a.x,a.F,a.x,a.D);d.fill();d.beginPath();d.shadowOffsetX=0;d.shadowOffsetY=0;d.shadowBlur=0;d.fillStyle=a.G;d.textAlign="center";d.textBaseline="middle";d.font=
"18px Arial";d.fillText(a.text,a.b,a.a+1)})}function na(a){a=y[a];d.beginPath();d.shadowColor=a.color;d.shadowBlur=a.shadowBlur;d.fillStyle=a.color;d.arc(a.b,a.a,a.c,0,2*Math.PI,!1);d.fill();d.beginPath();d.shadowColor="#191919";d.shadowBlur=2;d.strokeStyle="white";d.lineWidth=4;d.lineCap="round";var b=a.c-4;d.moveTo(a.b-b,a.a);d.lineTo(a.b+b,a.a);d.moveTo(a.b,a.a-b);d.lineTo(a.b,a.a+b);d.stroke()}
function X(){z.forEach(function(a){d.beginPath();d.shadowColor=a.shadowColor;d.shadowOffsetX=1;d.shadowOffsetY=1;d.shadowColor=a.shadowColor;d.shadowBlur=a.shadowBlur;d.strokeStyle=a.color;d.lineWidth=a.width;d.moveTo(a.g,a.h);d.bezierCurveTo(a.m,a.o,a.s,a.u,a.j,a.l);d.stroke()})}function S(a){a=void 0===a?!1:a;!1===a?(W(),X(),Y()):(W(),X(),Y(),na(a))}function ka(){for(var a=0;a<A.length&&r!=A[a][0];a++);return A[a]}
function la(){var a=[];z.forEach(function(b){M.forEach(function(e){b.i!=e&&b.f!=e||!1!==a.includes(b)||a.push(b)})});return a}function ma(a,b){var e=x[r].b-a,g=x[r].a-b;M.forEach(function(h){x[h].b-=e;x[h].a-=g;Z(h)})}function oa(a,b){var e=t-a,g=u-b;x.forEach(function(h){h.b-=e;h.a-=g})}function sa(){A.forEach(function(a,b,e){r==a[0]&&(a.push(x.length-1),e.push([x.length-1]));a.forEach(function(g,h,va){0<h&g==r&&va.push(x.length-1)})})}
function ra(a){a=void 0===a?!1:a;var b=Object.assign({},ba);b.f=r;!1!==a?(b.f=r,b.i=a):b.i=x.length-1;b.color=H;a=[];a.push(b);V(a);z.push(b)}function R(){""==C.value?x[K].text=da:(x[K].text=C.value,x[K].G="black");B=Math.round(d.measureText(x[K].text).width);x[K].width=B+35;F=B+25;C.style.width=B+10+"px";C.style.left=x[K].b-B/2-5+"px";Z(K);S(K)}function ta(){H!=O.value&&(H=O.value,z.forEach(function(a){a.f==K&&(a.color=H)}))}function ua(){!0===q&&(ta(),O.remove(),q=!1)}
function wa(){!0===p&&(R(),C.remove(),p=!1)}function ja(){M=ka();N=la();var a=[],b=[],e=[];M.forEach(function(h){a.push(x[h]);b.push(y[h])});for(var g=0;g<A.length;g++)if(A[g][0]==r){e=A[g];A.splice(g,1);break}r=n=m=I=!1;ua();wa();xa(e);ya();za(b);Aa(a);Ba();pa();V();S()}function xa(a){a.forEach(function(b){A.forEach(function(e,g,h){!0===e.includes(b)&&h[g].splice(h[g].indexOf(b),1);0==e.length&&h.splice(g,1)})})}function za(a){a.forEach(function(b){y.splice(y.indexOf(b),1)})}
function Aa(a){a.forEach(function(b){x.splice(x.indexOf(b),1)})}function ya(){N.forEach(function(a){z.splice(z.indexOf(a),1)})}
function Ba(){z.forEach(function(a){x.forEach(function(b,e){a.i==b.index&b.index!=e&&(A.forEach(function(g){1==g.includes(a.i)&&(g[g.indexOf(a.i)]=e)}),a.i=e,b.index=e,"branch"==b.text.split(" ")[0]&&(b.text="branch "+String(e)));a.f==b.index&b.index!=e&&(A.forEach(function(g){1==g.includes(a.f)&&(g[g.indexOf(a.f)]=e)}),a.f=e,b.index=e,"branch"==b.text.split(" ")[0]&&(b.text="branch "+String(e)))})})}
function qa(){if(!1===I&!1===J){I=J=!0;document.body.style.cursor="pointer";var a=x[r];F=a.width;G=a.height;ca=a.c;H=a.color;a.shadowColor=a.color;a.color="white";a.shadowBlur=0;var b=y[r];b.b=a.b;b.a=a.y;b.c=4;b.shadowBlur=0;L=Ca();L.forEach(function(g){g.shadowColor=g.color;g.shadowBlur=0});var e=setInterval(function(){a.width+=2;a.height+=4;a.c-=2;a.shadowBlur+=3;b.a-=6;b.c+=1;b.shadowBlur+=3;L.forEach(function(g){g.shadowBlur+=3});Z(r);S(r)},20);setTimeout(function(){clearInterval(e);a.shadowBlur=
18;b.shadowBlur=18;b.c=10;L.forEach(function(g){g.shadowBlur=18});Z(r);U(r);S(r);!1===q&&(q=!0,document.body.insertAdjacentHTML("afterend",'<input type="color" id="input-color">'),O=document.getElementById("input-color"),O.value=H,O.style.left=x[r].b-12+"px",O.style.top=x[r].a-2+G/2+"px");K=r;J=!1},120)}}
function T(){if(!0===I&!1===J){J=!0;var a=y[K],b=x[K];ua();wa();document.body.style.cursor="default";var e=setInterval(function(){b.width-=2;b.height-=4;b.c+=2;b.shadowBlur-=3;--a.c;a.shadowBlur-=3;L.forEach(function(g){g.shadowBlur-=3});Z(K);S(K)},20);setTimeout(function(){clearInterval(e);b.width=F;b.height=G;b.c=ca;b.color=H;b.shadowColor="#191919";b.shadowBlur=18;a.shadowBlur=18;a.c=10;L.forEach(function(g){g.shadowColor="black";g.shadowBlur=18});Z(K);U(K);S();J=I=!1},120)}}
function Ca(){var a=[];z.forEach(function(b){r==b.f&&a.push(b)});return a}x.push(Object.assign({},D));y.push(Object.assign({},aa));Z(0);S();
