var c=document.getElementById("Canvas"),d=c.getContext("2d"),f=c.width=window.innerWidth,k=c.height=window.innerHeight,l=!1,m=!1,n=!1,p=!1,q=!1,r=!1,t=0,u=0,v=0,aa=0,w=[],x=[],y=[],z=[[0]],A,B,ba={index:0,text:"New Mind",G:"white",color:"#FFA500",shadowColor:"#191919",shadowBlur:18,b:f/2,a:k/2,x:0,y:0,width:105,height:30,c:15,m:0,o:0,s:0,u:0,B:0,C:0,A:0,D:0,F:0,v:0},ca={color:"aqua",shadowBlur:18,x:0,y:0,b:0,a:0,c:10},da={f:0,i:0,color:"#FFA500",shadowColor:"black",shadowBlur:18,width:2,g:0,h:0,j:0,
l:0,m:0,o:0,s:0,u:0},C="#7FFF00 #00FFFF #FF00FF #FF4500 #4682B4 #4B0082 #FF0000 #e096e9 #e68782 #efa670 #9ed56b #67d7c4 #b4b4b4 #0da7d3 #3e8975 #69b500 #e8e525 #ffaa38 #a65427".split(" "),D,E,F,ea,fa,G=!1,H=!1,I=!1,J=!1,K=[],L=[],M=[],N,O;function ha(){O=!1;for(var a=0;a<w.length;a++)if(t>w[a].x&t<w[a].x+w[a].width&u>w[a].y-30&u<w[a].y+w[a].height+15){O=a;break}return O}c.addEventListener("mousedown",function(a){l=!0;v=a.offsetX;aa=a.offsetY;t=a.offsetX;u=a.offsetY;!0===m&!1===n&&(L=ia(),M=ja())});
c.addEventListener("mousemove",function(a){if(!1===H){if(!1===l){if(!1===m)r=ha(),m=!1!==r;else{var b=x[r];O=!1;t>b.x&t<b.b+b.c&u>b.a-b.c&u<b.a+b.c&&(O=r);r=O;!1!==r?n=!0:(n=!1,b=w[J],O=!1,t>b.x&t<b.x+b.width&u>b.y-30&u<b.y+b.height+15&&(O=J),r=O,m=!1!==r)}!0===m&&ka();J!==r&&la();!0===n?ma():I=!1}else{!0===m&!1===n&&(P(),Q(),na(a.offsetX,a.offsetY),R(r),S(M),T());if(!0===n){P();Q();b=a.offsetY;var g=x[r];g.b=a.offsetX;g.a=b;g.x=g.b-g.c;g.y=g.a-g.c;U();V();b=a.offsetX;g=a.offsetY;d.beginPath();d.shadowOffsetX=
0;d.shadowOffsetY=0;d.shadowColor="aqua";d.shadowBlur=18;d.strokeStyle="#3c2c3e";d.lineWidth=2;d.moveTo(w[r].b,w[r].a);d.lineTo(b,g);d.stroke();W();oa(r)}!1===m&!1===n&&(pa(a.offsetX,a.offsetY),qa(),S(),T(r))}t=a.offsetX;u=a.offsetY}});
c.addEventListener("mouseup",function(a){l=!1;if(!0===m&!0===n){R(r);var b=a.offsetX,g=a.offsetY,e=ha();if(!1===e){e=Object.assign({},ba);e.text="branch "+String(w.length);e.width=Math.round(d.measureText(e.text).width+25);e.b=b;e.a=g;for(b=C[Math.floor(Math.random()*(C.length-0))+0];b==F;)b=C[Math.floor(Math.random()*(C.length-0))+0],console.log("\u0421\u043e\u0432\u043f\u0430\u0434\u0435\u043d\u0438\u0435 \u0446\u0432\u0435\u0442\u0430 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e");
e.color=b;e.index=w.length;w.push(e);X(w.length-1);ra();b=Object.assign({},ca);x.push(b);sa()}else ra(e)}v==a.offsetX&aa==a.offsetY&&!0===m&!1===p&!1===n&&!1===p&&(p=!0,document.body.insertAdjacentHTML("afterend",'<input id="input-text">'),B=document.getElementById("input-text"),"branch"==w[r].text.split(" ")[0]||"New Mind"==w[r].text?(fa=w[r].text,B.value=""):B.value=w[r].text,A=Math.round(d.measureText(w[r].text).width),w[r].width=A+35,D=A+25,B.style.width=A+10+"px",B.style.left=w[r].b-A/2-5+"px",
B.style.top=w[r].a-10+"px",B.focus(),Z());!1===q&!0===m&&(T(r),ta())});document.addEventListener("keyup",function(a){"Delete"==a.key&!0===m&&ua();"Enter"==a.key&&deleteInput();!0===p&&Z()});window.addEventListener("resize",function(){f=c.width=window.innerWidth;k=c.height=window.innerHeight;T()});function qa(){w.forEach(function(a,b){X(b)})}
function X(a){a=w[a];a.x=a.b-a.width/2;a.y=a.a-a.height/2;var b=a.c/3;a.m=a.y+a.c;a.o=a.y+b;a.s=a.x+b;a.u=a.x+a.c;a.B=a.x+a.width-a.c;a.C=a.x+a.width-b;a.A=a.x+a.width;a.D=a.y+a.height-a.c;a.F=a.y+a.height-b;a.v=a.y+a.height}function R(a){var b=x[a];a=w[a];b.b=a.b;b.a=a.a-a.height/2-20;b.x=b.b-b.c;b.y=b.a-b.c}
function S(a){a=void 0===a?y:a;a.forEach(function(b){b.g=w[b.f].b;b.h=w[b.f].a;b.j=w[b.i].b;b.l=w[b.i].a;Math.abs(b.g-b.j)>Math.abs(b.h-b.l)?(b.m=b.g,b.o=b.l,b.s=b.j,b.u=b.h,b.b=b.g+(b.j-b.g)/2,b.a=b.h+(b.l-b.h)/2):(b.m=b.j,b.o=b.h,b.s=b.g,b.u=b.l,b.b=b.g-(b.g-b.j)/2,b.a=b.h-(b.h-b.l)/2)})}function U(){d.clearRect(0,0,f,k)}
function W(){w.forEach(function(a){d.beginPath();d.shadowColor=a.shadowColor;d.shadowBlur=a.shadowBlur;d.fillStyle=a.color;d.moveTo(a.x,a.m);d.bezierCurveTo(a.x,a.o,a.s,a.y,a.u,a.y);d.lineTo(a.B,a.y);d.bezierCurveTo(a.C,a.y,a.A,a.o,a.A,a.m);d.lineTo(a.A,a.D);d.bezierCurveTo(a.A,a.F,a.C,a.v,a.B,a.v);d.lineTo(a.u,a.v);d.bezierCurveTo(a.s,a.v,a.x,a.F,a.x,a.D);d.fill();d.beginPath();d.shadowOffsetX=0;d.shadowOffsetY=0;d.shadowBlur=0;d.fillStyle=a.G;d.textAlign="center";d.textBaseline="middle";d.font=
"18px Arial";d.fillText(a.text,a.b,a.a+1)})}function oa(a){a=x[a];d.beginPath();d.shadowColor=a.color;d.shadowBlur=a.shadowBlur;d.fillStyle=a.color;d.arc(a.b,a.a,a.c,0,2*Math.PI,!1);d.fill();d.beginPath();d.shadowColor="#191919";d.shadowBlur=2;d.strokeStyle="white";d.lineWidth=4;d.lineCap="round";var b=a.c-4;d.moveTo(a.b-b,a.a);d.lineTo(a.b+b,a.a);d.moveTo(a.b,a.a-b);d.lineTo(a.b,a.a+b);d.stroke()}
function V(){y.forEach(function(a){d.beginPath();d.shadowColor=a.shadowColor;d.shadowOffsetX=1;d.shadowOffsetY=1;d.shadowColor=a.shadowColor;d.shadowBlur=a.shadowBlur;d.strokeStyle=a.color;d.lineWidth=a.width;d.moveTo(a.g,a.h);d.bezierCurveTo(a.m,a.o,a.s,a.u,a.j,a.l);d.stroke()})}function T(a){a=void 0===a?!1:a;!1===a?(U(),V(),W()):(U(),V(),W(),oa(a))}function ia(){for(var a=0;a<z.length&&r!=z[a][0];a++);return z[a]}
function ja(){var a=[];y.forEach(function(b){L.forEach(function(g){b.i!=g&&b.f!=g||!1!==a.includes(b)||a.push(b)})});return a}function na(a,b){var g=w[r].b-a,e=w[r].a-b;L.forEach(function(h){w[h].b-=g;w[h].a-=e;X(h)})}function pa(a,b){var g=t-a,e=u-b;w.forEach(function(h){h.b-=g;h.a-=e})}function sa(){z.forEach(function(a,b,g){r==a[0]&&(a.push(w.length-1),g.push([w.length-1]));a.forEach(function(e,h,Y){0<h&e==r&&Y.push(w.length-1)})})}
function ra(a){a=void 0===a?!1:a;var b=Object.assign({},da);b.f=r;!1!==a?(b.f=r,b.i=a):b.i=w.length-1;b.color=F;a=[];a.push(b);S(a);y.push(b)}function Z(){""==B.value?w[J].text=fa:(w[J].text=B.value,w[J].G="black");A=Math.round(d.measureText(w[J].text).width);w[J].width=A+35;D=A+25;B.style.width=A+10+"px";B.style.left=w[J].b-A/2-5+"px";X(J);T(J)}
function ta(){!1===q&&(q=!0,document.body.insertAdjacentHTML("afterend",'<input type="color" id="input-color">'),N=document.getElementById("input-color"),N.value=F,N.style.left=w[r].b-12+"px",N.style.top=w[r].a-2+E/2+"px")}function va(){F!=N.value&&(F=N.value,y.forEach(function(a){a.f==J&&(a.color=F)}))}function P(){!0===q&&(va(),N.remove(),q=!1)}function Q(){!0===p&&(Z(),B.remove(),p=!1)}
function ua(){L=ia();M=ja();var a=[],b=[],g=[];L.forEach(function(h){a.push(w[h]);b.push(x[h])});for(var e=0;e<z.length;e++)if(z[e][0]==r){g=z[e];z.splice(e,1);break}r=n=m=G=!1;P();Q();wa(g);xa();ya(b);za(a);Aa();qa();S();T()}function wa(a){a.forEach(function(b){z.forEach(function(g,e,h){!0===g.includes(b)&&h[e].splice(h[e].indexOf(b),1);0==g.length&&h.splice(e,1)})})}function ya(a){a.forEach(function(b){x.splice(x.indexOf(b),1)})}function za(a){a.forEach(function(b){w.splice(w.indexOf(b),1)})}
function xa(){M.forEach(function(a){y.splice(y.indexOf(a),1)})}function Aa(){y.forEach(function(a){w.forEach(function(b,g){a.i==b.index&b.index!=g&&(z.forEach(function(e){1==e.includes(a.i)&&(e[e.indexOf(a.i)]=g)}),a.i=g,b.index=g,"branch"==b.text.split(" ")[0]&&(b.text="branch "+String(g)));a.f==b.index&b.index!=g&&(z.forEach(function(e){1==e.includes(a.f)&&(e[e.indexOf(a.f)]=g)}),a.f=g,b.index=g,"branch"==b.text.split(" ")[0]&&(b.text="branch "+String(g)))})})}
function ka(){if(!1===G&!1===H){G=H=!0;document.body.style.cursor="pointer";var a=w[r];D=a.width;E=a.height;ea=a.c;F=a.color;a.shadowColor=a.color;a.color="white";a.shadowBlur=0;var b=x[r];b.b=a.b;b.a=a.y;b.c=4;b.shadowBlur=0;K=Ba();K.forEach(function(e){e.shadowColor=e.color;e.shadowBlur=0});var g=setInterval(function(){a.width+=2;a.height+=4;a.c-=2;a.shadowBlur+=3;b.a-=6;b.c+=1;b.shadowBlur+=3;K.forEach(function(e){e.shadowBlur+=3});X(r);T(r)},20);setTimeout(function(){clearInterval(g);a.shadowBlur=
18;b.shadowBlur=18;b.c=10;K.forEach(function(e){e.shadowBlur=18});X(r);R(r);T(r);ta();J=r;H=!1},120)}}
function la(){if(!0===G&!1===H){H=!0;var a=x[J],b=w[J];P();Q();document.body.style.cursor="default";var g=setInterval(function(){b.width-=2;b.height-=4;b.c+=2;b.shadowBlur-=3;--a.c;a.shadowBlur-=3;K.forEach(function(e){e.shadowBlur-=3});X(J);T(J)},20);setTimeout(function(){clearInterval(g);b.width=D;b.height=E;b.c=ea;b.color=F;b.shadowColor="#191919";b.shadowBlur=18;a.shadowBlur=18;a.c=10;K.forEach(function(e){e.shadowColor="black";e.shadowBlur=18});X(J);R(J);T();H=G=!1},120)}}
function ma(){if(!1===H&!0===n&!1===I){I=H=!0;var a=x[r],b=6,g=a.b,e=a.a,h=0,Y=setInterval(function(){b-=.3;h=3>b?h-1:h+1;a.b=0*Math.cos(b)+h*Math.sin(b);a.a=-0*Math.sin(b)+h*Math.cos(b);a.b+=g;a.a+=e;T(r)},20);setTimeout(function(){clearInterval(Y);R(r);T(r);H=!1},420)}}function Ba(){var a=[];y.forEach(function(b){r==b.f&&a.push(b)});return a}w.push(Object.assign({},ba));x.push(Object.assign({},ca));X(0);T();
